---
services:
  app:
    image: mcr.microsoft.com/devcontainers/universal:linux
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    environment:
      PGHOST: db
      PGPASSWORD: codespace
    depends_on:
      - db
  db:
    image: postgres:latest
    volumes:
      - ./create-db-user.sql:/docker-entrypoint-initdb.d/create-db-user.sql
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
